services:
  server:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/www/html
      - /www/html/vendor/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - hive-mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - default

  ai:
    build:
      context: ./itvb23ows-hive-ai
    ports:
      - 5000:5000

volumes:
  hive-mysql-data:
