name: ci-tests
on: push
jobs:
  ci-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run composer
      uses: php-actions/composer@v6
      with:
        args: --ignore-platform-reqs
    
    - uses: php-actions/phpunit@v3

    - name: Composer
      run: composer install

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 11.2.5
        bootstrap: vendor/autoload.php
        configuration: test/phpunit.xml
        args: --coverage-text
