name: ci-tests
on: push
jobs:
  ci-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Run composer
      uses: php-actions/composer@v6
      with:
        php_version: 8.3
        args: --ignore-platform-reqs
    
    # - uses: php-actions/phpunit@v3
    - run: ./vendor/bin/phpunit tests
    # - name: PHPUnit Tests
    #   uses: php-actions/phpunit@master
    #   with:
    #     version: 11.2.5
    #     php_version: 8.3
    #     # bootstrap: vendor/autoload.php
    #     configuration: phpunit.xml
    #     args: --coverage-text

  qodana:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}