name: ci-tests
on: push
jobs:
  ci-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --ignore-platform-reqs --prefer-dist --no-progress

    # - name: Run composer
    #   uses: php-actions/composer@v6
    #   with:
    #     args: --ignore-platform-reqs
    
    # - uses: php-actions/phpunit@v3

    # - name: Composer
    #   run: composer install

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 11.2.5
        bootstrap: vendor/autoload.php
        configuration: test/phpunit.xml
        args: --coverage-text
